steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/myaccess-backend', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/myaccess-backend']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'myaccess-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myaccess-backend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=DJANGO_SETTINGS_MODULE=backend.settings_production,OPENAI_API_KEY=$$OPENAI_API_KEY'
      - '--port=8000'
      - '--memory=1Gi'
      - '--cpu=1'
    secretEnv: ['OPENAI_API_KEY']

# Store secrets in Secret Manager
secrets:
- kmsKeyName: projects/your-project-id/locations/global/keyRings/your-keyring/cryptoKeys/your-key
  secretEnv:
    OPENAI_API_KEY: 'your-encrypted-api-key-here'

# Keep the last 3 images to avoid storage issues
images:
  - gcr.io/$PROJECT_ID/myaccess-backend
